export const chinaRegions = [
  { province: '北京市', cities: ['北京市'] },
  { province: '天津市', cities: ['天津市'] },
  { province: '上海市', cities: ['上海市'] },
  { province: '重庆市', cities: ['重庆市'] },
  { province: '河北省', cities: ['石家庄市', '唐山市', '保定市', '廊坊市'] },
  { province: '山西省', cities: ['太原市', '大同市', '长治市'] },
  { province: '辽宁省', cities: ['沈阳市', '大连市', '鞍山市'] },
  { province: '吉林省', cities: ['长春市', '吉林市'] },
  { province: '黑龙江省', cities: ['哈尔滨市', '齐齐哈尔市'] },
  { province: '江苏省', cities: ['南京市', '无锡市', '常州市', '苏州市', '南通市'] },
  { province: '浙江省', cities: ['杭州市', '宁波市', '温州市', '嘉兴市'] },
  { province: '安徽省', cities: ['合肥市', '芜湖市', '马鞍山市'] },
  { province: '福建省', cities: ['福州市', '厦门市', '泉州市'] },
  { province: '江西省', cities: ['南昌市', '赣州市'] },
  { province: '山东省', cities: ['济南市', '青岛市', '烟台市', '潍坊市'] },
  { province: '河南省', cities: ['郑州市', '洛阳市', '许昌市'] },
  { province: '湖北省', cities: ['武汉市', '襄阳市', '宜昌市'] },
  { province: '湖南省', cities: ['长沙市', '株洲市', '湘潭市'] },
  { province: '广东省', cities: ['广州市', '深圳市', '佛山市', '东莞市', '中山市'] },
  { province: '海南省', cities: ['海口市', '三亚市'] },
  { province: '四川省', cities: ['成都市', '绵阳市', '德阳市'] },
  { province: '贵州省', cities: ['贵阳市', '遵义市'] },
  { province: '云南省', cities: ['昆明市', '曲靖市'] },
  { province: '陕西省', cities: ['西安市', '宝鸡市'] },
  { province: '甘肃省', cities: ['兰州市'] },
  { province: '青海省', cities: ['西宁市'] },
  { province: '台湾省', cities: ['台北市', '高雄市'] },
  { province: '内蒙古自治区', cities: ['呼和浩特市', '包头市'] },
  { province: '广西壮族自治区', cities: ['南宁市', '柳州市'] },
  { province: '西藏自治区', cities: ['拉萨市'] },
  { province: '宁夏回族自治区', cities: ['银川市'] },
  { province: '新疆维吾尔自治区', cities: ['乌鲁木齐市'] },
  { province: '香港特别行政区', cities: ['香港'] },
  { province: '澳门特别行政区', cities: ['澳门'] }
];

export const worldCountryOptions = [
  '美国',
  '加拿大',
  '墨西哥',
  '巴西',
  '英国',
  '德国',
  '法国',
  '意大利',
  '西班牙',
  '荷兰',
  '瑞士',
  '瑞典',
  '波兰',
  '俄罗斯',
  '日本',
  '韩国',
  '新加坡',
  '马来西亚',
  '泰国',
  '越南',
  '印度',
  '印度尼西亚',
  '菲律宾',
  '澳大利亚',
  '新西兰',
  '阿联酋',
  '沙特阿拉伯',
  '土耳其',
  '南非'
];
